version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: csv-parse
    versions:
    - 4.15.0
    - 4.15.1
    - 4.15.3
  - dependency-name: ejs
    versions:
    - 3.1.5
